### ISSUE TITLE
vault hunters 3rd edition server errors

### ISSUE THREAD

**Issue by GodGamer1** [DoubleDoorDevelopment/Sunburn#5]
i discussed with curseforge discord server moderator and he told me to report here an issue about client side mode errors in the latest server pack

when i run run.bat i get this error: 
java.lang.NullPointerException: Cannot invoke "net.creeperhost.ftbbackups.org.quartz.Scheduler.isShutdown()" because "net.creeperhost.ftbbackups.FTBBackups.scheduler" is null
        at TRANSFORMER/ftbbackups2@1.0.17/net.creeperhost.ftbbackups.FTBBackups.killOutThreads(FTBBackups.java:110)
        at java.base/java.lang.Thread.run(Thread.java:833)

with this latest log file:

[latest.log](https://github.com/DoubleDoorDevelopment/Sunburn/files/10844451/latest.log)

**Comment by Claycorp** [comment]
1. `Sunburn` isn't even in this modpack.
2. There's nothing I can fix with this.
3. Whatever moderator told you to report this should have just told you to remove `ToroHealth` instead.... They should have known better than to tell you to open a support ticket, Useless support.
