### ISSUE TITLE
Minecraft crashing

### ISSUE THREAD

**Issue by MAHHT1N** [DoubleDoorDevelopment/Sunburn#7]
The game loads for a bit then just crashes before the main menu pops up. 
The game crashed whilst rendering overlay
Error: com.jozufozu.flywheel.backend.loading.ShaderLoadingException: Could not load all shaders, see log for details

**Comment by Claycorp** [comment]
Uh.... unless you have something else to post with this related to Sun Burn your in the wrong place. I don't make flywheel.
